### ISSUE TITLE
Debug Assertion Error in Visual Studio

### ISSUE THREAD

**Issue by jinha3411** [YutaItoh/3D-Eye-Tracker#13]
Hi.
Whenever I call,
`cv::findContours(threshLow, contoursLow, CV_RETR_EXTERNAL, CV_CHAIN_APPROX_NONE);`
it produces assertion error after returning from the function.
Do you know why this happens?

**Comment by NuncObdurat** [comment]
Please copy and paste the exact assertion error.

**Comment by jinha3411** [comment]
Debug Assertion Failed!
File: f/dd/vctools/crt/crtw32/misc/dbgdel.cpp
Line: 52
Expression: _BLOCK_TYPE_IS_VALID(pHead->nBlockUse)

**Comment by NuncObdurat** [comment]
Not sure about this. It's not an assertion that we put in. Perhaps try compiling the release version?
