### ISSUE TITLE
Running in Visual Studio 2013 (vc120)

### ISSUE THREAD

**Issue by jinha3411** [YutaItoh/3D-Eye-Tracker#14]
I am trying to compile your solution with Visual Studio, but it seems like compiled external libraries are not usable under vc120 platform toolset. (I have only seen platform conflict issues with Ceres for now).
And I am having a hard time to compile ceres libraries under vc12. Do you have any compiled libraries or any link that I can refer to?

**Comment by YutaItoh** [comment]
Hi @jinha3411 , thx for trying out our code and srry to hear that you had a hard time to compile an external library.
Perhaps this article could help you?
"How to Use Ceres-Solver in a New Project (Visual Studio 2015)"
https://groups.google.com/forum/#!topic/ceres-solver/3vIF3EF7C1M
