### ISSUE TITLE
Theoretical problem

### ISSUE THREAD

**Issue by tcc828** [YutaItoh/3D-Eye-Tracker#15]
Thank you for sharing, is there any relevant essay or document to help understand the corresponding methodology?

**Comment by NuncObdurat** [comment]
Here are three of our papers that describe the building of the model and some of the processes that we use. 

General process:
Swirski, L., & Dodgson, N. (2013). A fully-automatic, temporal approach to single camera, glint-free 3d eye model fitting. Proc. PETMEI.

Eye model for calibration:
Itoh, Y., & Klinker, G. (2014, March). Interaction-free calibration for optical see-through head-mounted displays based on 3d eye localization. In 3D User Interfaces (3DUI), 2014 IEEE Symposium on (pp. 75-82). IEEE.

Pupil fitter on P4:
Orlosky, J., Itoh, Y., Ranchet, M., Kiyokawa, K., Morgan, J., & Devos, H. (2017). Emulation of physician tasks in eye-tracked virtual reality for remote diagnosis of neurodegenerative disease. IEEE transactions on visualization and computer graphics, 23(4), 1302-1311.
