### ISSUE TITLE
Not an issue, just a question regarding accuracy

### ISSUE THREAD

**Issue by jinha3411** [YutaItoh/3D-Eye-Tracker#16]
First of all, I want to address that I really thank for all of your work.
I am really being benefited by using your program since all the program and I use for my research topic runs under C++ and there is no official C++ support by pupil labs.
The reason why I am starting this thread is that I am wondering how accurate or "close" this program tries to resemble the official pupil labs' pupil detector algorithm in terms of detection accuracy.
I know your calibration routine is simply to rotate eyeball in initialization stages while pupil labs ask to follow the marker with the world camera.
Your program runs 2D ellipse fitting with several filters but does it essentially perform the same detection algorithms?
When my eyes are half-way closed, the detector finds a false pupil area which tends to be located outside of my Iris.
I know that this can be filtered out by computing the reliability. Regarding this matter, does it perform same reliability computation?

One last question is that pupil capture program by pupil labs gives a diameter of Pupil in mm unit. Do you know how they calculate this even though I have never calibrated the camera? 
I know you provide the camera intrinsic matrix. 

Anyway, I really appreciate your work. Thank you

**Comment by NuncObdurat** [comment]
Hi Jinha,

Thanks for the comments.

Our detector is very different than the one used by pupil labs. One unique feature of our pupil detector is that it can be run on any individual frame and does not require previous frames to establish a baseline.  We do actually have a filter within the pupilFitter algorithm (bool badEllipseFilter(RotatedRect current, int maxSize)), but it is not used by default in the event that other developers want to use their own filters. There is also a method for computing reliability in eye_model_updater (double EyeModelUpdater::compute_reliability(cv::Mat &img, sef::Ellipse2D<double> &el, std::vector<cv::Point2f> &inlier_pts)). Let us know if these help. 

Secondly, we are currently working on a version of the code that compensates for drift by updating the eyeball model over time, something that pupil labs code already does. We don't have as much bandwidth as the engineers a pupil labs (only 2 professors are maintaining this code), so it may be a few more months before anything is released. 

The pupil diameter question is something that Yuta can probably answer better, but I think the mm unit is indeed computed based on whatever intrinsic matrix you provide, or the default matrix based on the pupil labs cameras if you don't calibrate your own camera.

**Comment by jinha3411** [comment]
Regarding compute_reliability, I believe it computes the reliability of the pupil, which I believe it is kind of extension of badEllipseFilter since it also tries to filter out the false pupil ellipse. I assume it needs a 3D eye model which can be initialized during startup and it uses the camera intrinsic matric (correct me if I am wrong). Then the reliability that the program computes must be based on the calibration data that your program provided. Does this have an effect on the accurate computation of the reliability?

**Comment by NuncObdurat** [comment]
I believe so, but if your camera's intrinsic matrix is relatively close to the default matrix, error will be quite low. You could always try to output a few frames along with the reliability value outputs to verify this manually.

**Comment by jinha3411** [comment]
But, the focal length changes as I change the focus of the camera. Also, the intrinsic matrix that you load from your program seems different from what they use as default parameter. Can you tell me whether you calibrated the camera or not?

**Comment by NuncObdurat** [comment]
Adjusting the camera's focal depth by screwing it further in or out should not significantly change the size of the image unless you adding additional optics (like a wide FoV lens). 

I don't typically calibrate my cameras beforehand, but I think Yuta usually does. I'm not sure when or where those calibration parameters were taken, so you should ideally enter your own.

**Comment by jinha3411** [comment]
Thanks, I probably had to look into how I can calibrate this small camera. Thank you!
