### ISSUE TITLE
algorithm of this project？

### ISSUE THREAD

**Issue by chaipangpang** [YutaItoh/3D-Eye-Tracker#17]
Hello,i stay tuned this project Recently,and study some algorithm about this project by source code.
but,Can you provide an introduction to this algorithms?

**Comment by NuncObdurat** [comment]
Hello, 

There are many algorithms involved in this project. Would you like to know about a particular one? 

As a start, a few of our papers are listed in the thread below:
https://github.com/YutaItoh/3D-Eye-Tracker/issues/15
