### ISSUE TITLE
How to compile x86

### ISSUE THREAD

**Issue by chaipangpang** [YutaItoh/3D-Eye-Tracker#19]
hi, i want build x86 of vs2015,i have Configurated opencv (vc14, x86) and boost boost_1_62_0-msvc-32.0-.exe，but the compilation failed，what else do I need to do next?
and some others .dll and  .lib in ./external，does its affect compilation？

**Comment by NuncObdurat** [comment]
I think you may need to debug the compilation yourself. My biggest hint is to make sure that you are not mixing any x64 and x86 libraries, including all dependencies.
