### ISSUE TITLE
Is it possible to run the program in linux?

### ISSUE THREAD

**Issue by jorge-sanrod** [YutaItoh/3D-Eye-Tracker#20]
I'll like to run this program in a raspberry pi. can i compile without visual studio in ubuntu? 
If it can, what method would you have to use?

thanks for your time, regards.

**Comment by YutaItoh** [comment]
hi jorge-sanrod, 
Unfortunately we have not tried on Linux. As the code are written with open source libraries, it should be theoretically possible, but you would need to compile those related libraries by yourself.

**Comment by jorge-sanrod** [comment]
Thanks for your answer, I do not have much experience in Linux, but I will try it and if I'll be successful, I will write here how for others who need it.

**Comment by YutaItoh** [comment]
good luck! i believe some packages could simply be installed via package managers in linux.
