### ISSUE TITLE
camera features

### ISSUE THREAD

**Issue by jorge-sanrod** [YutaItoh/3D-Eye-Tracker#21]
Hi, you mention that the camera has an infrared LED, so the camera should not have an infrared filter? and is and is a minimum frame rate necessary?

Thanks and regards.

**Comment by NuncObdurat** [comment]
An IR cut filter is not desirable.  The camera should ideally filter out red, green and blue wavelengths, leaving only IR in the image. 

There is no minimum framerate (you can even run the algorithm on a series of sequential images), but we recommend at least 30Hz for real time use.

**Comment by jorge-sanrod** [comment]
thank you very much for your answer.
