### ISSUE TITLE
error C2440 

### ISSUE THREAD

**Issue by LIUMeng0823** [YutaItoh/3D-Eye-Tracker#22]
Hello! I followed the instruction in readme.txt. while I running `3d_eye_tracker.sln` in the build folder, error C2440 occurred. The detail showed as follows:

Error C2440	'<function-style-cast>': cannot convert from 'initializer list' to 'singleeyefitter::Ellipse2D<double>'  main  E:\program\gaze tracking\3D-Eye-Tracker master\singleeyefitter\singleeyefitter\singleeyefitter.h	42	

How to fix this error? Thanks!

**Comment by NuncObdurat** [comment]
Hi Liu Meng, 

Does that error show up when trying to compile the code without modifying it? We have never seen that error when trying to compile from scratch. It seems to be a type mismatch, so you may want to verify that all of your versions are consistent (OpenCV, bit-ness, compiled for 64 bit release, etc.).

**Comment by LIUMeng0823** [comment]
Thanks for your reply！
I use the same build environment(win10 64X  cmake 3.5.1 boost1.62 opencv3.1.0 VS2015) like you.
When I use cmake to build the project, some errors about the boost's version occurred but the configure process is successful, so I generated the 'sln' anyway. are those errors cause the problem?
<img width="960" alt="wechat screenshot_20180919131449" src="https://user-images.githubusercontent.com/35795039/45732276-24564e00-bc0e-11e8-914a-6ac6fe6e16c9.png">
<img width="960" alt="wechat screenshot_20180919131555" src="https://user-images.githubusercontent.com/35795039/45732283-2c15f280-bc0e-11e8-8c68-fba3123e2b77.png">
<img width="960" alt="wechat screenshot_20180919131541" src="https://user-images.githubusercontent.com/35795039/45732288-33d59700-bc0e-11e8-87fc-25764213cac9.png">

**Comment by NuncObdurat** [comment]
Hmm... That looks like it shouldn't affect the build, though I'm not an expert on boost dependencies. Yuta, any ideas?

**Comment by LIUMeng0823** [comment]
I have solved the problem by reinstall the boost1.62 and using the latest version of cmake3.12.2 to generate the project. it seems like cmake3.5.1 and boost1.62 conflicted in my computer.

**Comment by NuncObdurat** [comment]
Glad to hear it!
