### ISSUE TITLE
When using a web camera to track my eyes, I can't always get the gaze vector, why?

### ISSUE THREAD

**Issue by ANYMS-A** [YutaItoh/3D-Eye-Tracker#25]
Nice job! But I met a few problems when running your eye-tracker. 
I used a web camera (WIN2 USB2.0 PC Camera) to test the eye tracker. However, the result showed that I can't always obtain the gaze (normal) vector of my eye ball. Is there any solutions for this? I want the gaze vector could be obtained stably. 

Should I change another camera or update the camera calibration information in the "cameraintrinsics_eye.txt" file? Or I have to keep the positions of the camera and my head in a more stable status?

Another problem is that is there any paper or document that describe your eye tracking algorithm？ because I'd like to learn more details about your work.

Many thanks!

**Comment by NuncObdurat** [comment]
Hi Crissallan, 

Our algorithm is designed to work with near-eye infrared cameras, so it may not work with standard webcameras. The initial implementation of the tracker is described in the following publication: 

Itoh, Y., & Klinker, G. (2014, March). Interaction-free calibration for optical see-through head-mounted displays based on 3d eye localization. In 2014 IEEE symposium on 3d user interfaces (3dui) (pp. 75-82). IEEE.

Unfortunately the updated drift correction model is not yet published, but the above publication should get you started. 

Best,
Jason

**Comment by ANYMS-A** [comment]
> Hi Crissallan,
> 
> Our algorithm is designed to work with near-eye infrared cameras, so it may not work with standard webcameras. The initial implementation of the tracker is described in the following publication:
> 
> Itoh, Y., & Klinker, G. (2014, March). Interaction-free calibration for optical see-through head-mounted displays based on 3d eye localization. In 2014 IEEE symposium on 3d user interfaces (3dui) (pp. 75-82). IEEE.
> 
> Unfortunately the updated drift correction model is not yet published, but the above publication should get you started.
> 
> Best,
> Jason

Thank you so much!
