### ISSUE TITLE
Access is Denied

### ISSUE THREAD

**Issue by farzinmatin** [YutaItoh/3D-Eye-Tracker#26]
I did all the Prerequisite and requirements, But when run the program
get this error: ...\ALL_BUILD access is denied.
Do you know how can I solve this problem !?

**Comment by NuncObdurat** [comment]
This is possibly due to your folder permissions or IDE configuration.

**Comment by farzinmatin** [comment]
The "3D-Eye-Tracker-master" folder is read-only, and there is no way to remove this read-only access.
Is there any solution for that? 
![image](https://user-images.githubusercontent.com/63727186/85349770-4515ab00-b53a-11ea-892b-9a4f7e57c0be.png)

**Comment by NuncObdurat** [comment]
If you're on a Windows machine with Administrator privileges, you should be able to change this. Also make sure that the build folder is not open in some other application or another instance of your IDE. In any event, this is likely a problem with your OS/setup rather than the code.
