### ISSUE TITLE
The program was stuck at the beginning

### ISSUE THREAD

**Issue by AllyCasablancas** [YutaItoh/3D-Eye-Tracker#30]
Hi.
I'm using 64-bit windows 10, visual studio 2015 and basically meet the requisites you mentioned. 
I compiled it with CMake and got the "build" folder with correct files in it. It all seems well and I successfully run the `main` project. 

But the program got stuck at main.cpp:224, in the function "fetchFrame". I checked out the content of the "fetchFrame" function. It is originated from "DirectShowFrameGrabber::getFrame" in DirectShowFrameGrabber.cpp, and the program stopped at line 526 of DirectShowFrameGrabber.cpp ( m_cv.wait(lk) ). The below image shows the result, it just stopped in the middle of the execution, and I didn't see the expected eye tracking frame or something.
![image](https://user-images.githubusercontent.com/51443980/108043354-fcd46b80-707b-11eb-8218-f28c29c7d13e.png)

I wonder if my compilation step was wrong. I open the .sln file in visual studio, set the "main" project as start up project, and press F5 to execute it.

Or it's because I didn't use the pupil-labs cameras? I used the built-in webcam on my laptop. Because I didn't care about the accuracy for now, I just want to run the program successfully first.  

Thank you!

**Comment by NuncObdurat** [comment]
It is very likely this has to do with your webcam, perhaps the resolution. It also looks like your webcam has been identified as an IR camera "USB2.0 HD IR UVC WebCam," but webcams are typically not infrared. I recommend testing with the pupil labs camera(s) first.
