### ISSUE TITLE
Cannot find Boost libraries

### ISSUE THREAD

**Issue by klaassr004** [YutaItoh/3D-Eye-Tracker#4]
Title says it all, but for more info:

CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1793 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: C:/local/boost_1_62_0

  Could not find the following static Boost libraries:

          boost_filesystem
          boost_system
          boost_timer
          boost_thread
          boost_date_time
          boost_chrono
          boost_regex
          boost_serialization

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:54 (find_package)

CMake Error at CMakeLists.txt:55 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by YutaItoh** [comment]
Hi @klaassr004 

Possible diagnosis questions I would ask to myself:
1. Is it built for Visual Studio 2015 x64?
2. Inside your Boost C++ SDK, does it have a `./lib64-msvc-14.0/` folder?
3. In `./CMakeLists.txt`, `set(BOOST_ROOT "C:/SDK/boost_1_62_0")` is set? (I assume it is, and it is set to `C:/local/boost_1_62_0`)
4.  In `./CMakeLists.txt`, `set(OpenCV_DIR "C:/SDK/opencv-3.1.0/build")` is set?

If the answers for 1&2 are No, then external libraries for a favored environment (e.g. msvc-12.0 environment) have to be  built manually.

**Comment by klaassr004** [comment]
@YutaItoh  thanks for your answer.
I see what the problem is now, I used to put in the wrong visual studio verson.
I kind of misread the VS versions, I had to select Visual studio 14 2015 win64. I feel kind of stupid now.
Anyway, thanks again for creating this software and helping me out!

**Comment by YutaItoh** [comment]
hi @klaassr004 , my pleasure. Please feel free to post any issues when you encounter them while using the software :)
FYI, a colleague of mine was able to build it on vc12 after compiling other external libraries, so it's in my to do list to update the external lib setup.
