### ISSUE TITLE
directshowframegrabber don't find pupil lab cams

### ISSUE THREAD

**Issue by SanghunNam** [YutaItoh/3D-Eye-Tracker#6]
How are you?
I use the window 10, visual studio 2015, MSI VR notebook.
First I installed the usb installer and I checked device manager and running capture program.
But when I run for testing, directshowframegrabber don't find pupil lab cam.
they found only the webcam in notebook.
do you have any idea or advice?

**Comment by YutaItoh** [comment]
Hi @SanghunNam,

I can raise several possible causes:

$1. Camera name mismatch

In the line:
https://github.com/YutaItoh/3D-Eye-Tracker/blob/master/main/main.cpp#L166
> eyecams[0] = std::make_unique<eye_tracker::EyeCameraDS>("Pupil Cam1 ID0"); //

can you double check if the passed camera name is the same as the one shown on other camera apps e.g. Skype or AMCap?
http://noeld.com/programs.asp?cat=video

$2. A compatibility issue between the camera and our DirectShow implementation :(

If this is the case, can you try the highgui camera grabber by replacing the line:
https://github.com/YutaItoh/3D-Eye-Tracker/blob/master/main/main.cpp#L166
with something like
> eyecams[0] = std::make_unique<eye_tracker::EyeCamera>(camera_indices[0], false);

this allows the program accessing a camera via OpenCV highgui module.

Hope the above info. helps.

**Comment by SanghunNam** [comment]
Thank you for your advice.
I think it's a hardware problem.
Because my new computer (windows 10) found the pupil lab cam.
In the device manger, pupil lab is inside Imaging device. It's possible to be found with directshow.
but my notebook can't recognize the pupil lab with imaging device. 
 thanks.
