### ISSUE TITLE
how can i check pupil diameter?

### ISSUE THREAD

**Issue by SanghunNam** [YutaItoh/3D-Eye-Tracker#7]
How are you?
I need pupil diameter for my research.
I'am checking your code for get the pupil diameter.
Can you explain it for easy?

**Comment by jason01234** [comment]
Hi SanghunNam. 

In the eye_model_updater.cpp file, there is a function that handles the 3D gaze vector on line 295. 
The radius of the pupil can be returned using c_end.radius. 

For example:
std::cout << "radius: " << c_end.radius << std::endl;
would print the pupil radius for every frame. Multiply by 2 to get the diameter. 

Hope this answers your question. 

Jason
